actuators:
    engine:
        output_pin: 1
        board_pin: 13
        frequency: 50
        duty:
            min: 0.065
            max: 0.115
        output:
            min: -20.0
            max: 20.0
    steering:
        output_pin: 2
        board_pin: 19
        frequency: 50
        duty:
            min: 0.065
            max: 0.115
        output:
            min: -1.0
            max: 1.0
